### ISSUE TITLE
Tracking issue: new colour system

### ISSUE THREAD

**Issue by jamwaffles** [jamwaffles/embedded-graphics#138]
This is a tracking issue for the colour features merged in #127. Comment here with issues found during implementation in drivers/projects.

**Comment by jamwaffles** [comment]
I can't remember if this was discussed by myself and @rfuest, but should `u8` be convertible to `BinaryColor`? Where `0` -> `BinaryColor::Off` and `> 0` -> `BinaryColor::On`? I have quite lot of example code in the SSD1306 crate that uses `1u8.into()` which I can't decide whether to keep or not.

**Comment by rfuest** [comment]
I think that `From<u8> for BinaryColor` shouldn't be implemented, because it is ambiguous. The conversion `u8` to `bool` would be a similar conversion, which is not implemented in rust and rust users are used to explicitly convert an integer to `bool` by using `i != 0`.

But `From<bool> for BinaryColor` might be a useful addition. What do you think?

**Comment by jamwaffles** [comment]
Good points!

> But From<bool> for BinaryColor might be a useful addition. What do you think?

That makes loads more sense, yeah let's do that

**Comment by jamwaffles** [comment]
Re #165, I think the docs could use a bit of clarifying around conversion behaviours and some common use cases.

**Comment by jamwaffles** [comment]
I'm going to close this issue in preference of just creating individual new issues against the 0.6.0 project to discuss findings from using the new colours.
