### ISSUE TITLE
Add DrawTarget adapter to perform automatic colour conversions

### ISSUE THREAD

**Issue by jamwaffles** [jamwaffles/embedded-graphics#446]
#440 introduces changes to make `DrawTarget` generic across colors. This is a useful feature, however in https://github.com/jamwaffles/embedded-graphics/pull/440#issuecomment-693431053 the point is raised that this may accidentally introduce slower automatic conversion if the wrong colour type is used. 

The suggested solution is a `DrawTarget` adapter akin to `TranslatedDrawTarget`, etc, which is an opt-in target which can perform the potentially costly automatic conversion for use cases that need it.

**Comment by rfuest** [comment]
IMO another advantage of this approach is that we can easily add different variants for color conversions that all use a similar API.

For example, e-g doesn't implement `From<RgbXXX>` for `GrayX`, because there are multiple ways of converting colors to grayscale (average of the RGB components, calculating luma, ...). We could later add specialized adapters for these conversion, in addition to the generic adapter that was suggested in the original comment and requires a `From<OtherColor>` impl.

A `map` type adapter, that takes a closure to convert from one color type to another, could also be a useful addition.
